### ISSUE TITLE
[BUG]Cannot manually install cuVS

### ISSUE THREAD

**Issue by Lion815** [rapidsai/cuvs#423]
**cuvs/build.sh failed**
Hi! I am trying to do some adjustment on your source code of cagra and check if it could work. However, I failed to manually install your cuvs package (without any modification).
Could you kindly tell me if there is a better way for me to complete it, or  help with the maunually installation problem.

```
/cuvs-branch-24.12$ ./build.sh python
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple
Processing ./python/cuvs
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/rapids_build_backend/impls.py", line 370, in prepare_metadata_for_build_wheel
          return _get_backend(config.build_backend).prepare_metadata_for_build_wheel(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/scikit_build_core/build/__init__.py", line 96, in prepare_metadata_for_build_wheel
          return _build_wheel_impl(
                 ^^^^^^^^^^^^^^^^^^
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/scikit_build_core/build/wheel.py", line 175, in _build_wheel_impl
          return _build_wheel_impl_impl(
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/scikit_build_core/build/wheel.py", line 232, in _build_wheel_impl_impl
          metadata = get_standard_metadata(pyproject, settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/scikit_build_core/build/metadata.py", line 40, in get_standard_metadata
          metadata = StandardMetadata.from_pyproject(new_pyproject_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/scikit_build_core/_vendor/pyproject_metadata/__init__.py", line 238, in from_pyproject
          version = packaging.version.Version(version_string) if version_string else None
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/share/public/chenzk/Miniconda3/envs/transformer/lib/python3.11/site-packages/packaging/version.py", line 202, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      packaging.version.InvalidVersion: Invalid version: '../../../VERSION'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

My environment is:
Miniconda 24.7.1
python 3.11.10
cmake  3.27.4
gcc       11.4.0
nvcc      12.1
packaging 24.1

**Comment by bdice** [comment]
The `VERSION` file needed here is a symlink. The path `cuvs-branch-24.12/python/cuvs/cuvs/VERSION` should be a symlink that points to `cuvs-branch-24.12/VERSION`. You can see it on GitHub here: https://github.com/rapidsai/cuvs/blob/branch-24.12/python/cuvs/cuvs/VERSION

Note that to get this symlink, you must use `git` to clone the repository. The symlink is not present in the .zip archive of this repository, because .zip files do not support symlinks. I am guessing that you might have downloaded the .zip file of this repository, based on the name of your directory (`cuvs-branch-24.12`).

You can try `git clone https://github.com/rapidsai/cuvs.git` to clone from GitHub.

**Comment by Lion815** [comment]
Thanks! I will try.
